// Generated by CoffeeScript 1.10.0
(function() {
  var types,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  types = ["Administrator", "Student", "Instructor", "Observer"];

  this.load_account_page = function() {
    return api_call("GET", "/api/user/info", {}).done(function(result) {
      var account, i, len, panel, ref;
      if (result.success === 1) {
        account = result.data;
        $("#name").html(account.name);
        $("#account-name").val(account.name);
        $("#avatar").attr("src", "//www.gravatar.com/avatar/" + account.email_hash + "?size=512");
        $("#email").html(account.email);
        $("#-account-email").val(account.email);
        $("#email_container").attr("href", "mailto:" + account.email);
        $("#type").html(types[account.type]);
        ref = result.data.panels;
        for (i = 0, len = ref.length; i < len; i++) {
          panel = ref[i];
          $("#" + panel).slideDown("fast");
        }
        if (indexOf.call(result.data.panels, "_team") >= 0 && (account.type !== 2)) {
          $("#leave_form").attr("action", "javascript:remove_user('" + account.uid + "');");
          $("#leave_form").attr("onsubmit", "remove_user('" + account.uid + "');return false;");
          api_call("GET", "/api/team/info", {}).done(function(result2) {
            var team;
            team = result2.data;
            $("#team_name").html(team.teamname);
            $("#team-name").val(team.teamname);
            if (team.school) {
              $("#team-school").val(team.school);
            }
            $("#public_profile_link").attr("href", "/team?" + team.teamname);
            $("#leave_confirm").attr("placeholder", team.teamname);
            if (account.teamowner === true) {
              $("#team-school").removeAttr("disabled");
              api_call("GET", "/api/team/schools", {}).done(function(result3) {
                return $("#team-school").typeahead({
                  items: 10,
                  minLength: 2,
                  source: result3.data
                });
              });
              $("#team-name").removeAttr("disabled");
              $("#team-help").slideDown("fast");
              return api_call("GET", "/api/team/join_code", {}).done(function(result3) {
                if (result3.success === 1) {
                  $("#team-join-code").val(result3.data);
                  return $("#join_code_row").slideDown("fast");
                }
              });
            }
          });
          return api_call("GET", "/api/team/members", {}).done(function(result2) {
            var html, j, len1, member, ref1, you;
            if (result2.success === 1) {
              html = "";
              ref1 = result2.data;
              for (j = 0, len1 = ref1.length; j < len1; j++) {
                member = ref1[j];
                you = member.uid === account.uid;
                html += "<li class='list-group-item' id='remove_" + member.uid + "' style='display:none;'></li>";
                html += "<li class='list-group-item' id='member_" + member.uid + "'>";
                html += "<span style='font-weight: " + (you != null ? you : {
                  "bold": "normal"
                }) + ";'>" + member.name + "</span><br />";
                html += "<small><a href='mailto:" + member.email + "' class='NO_HOVER_UNDERLINE_DAMMIT'><span class='fa fa-envelope'></span> &nbsp; " + member.email + "</a></small>";
                if (account.teamowner === true && member.uid !== account.uid) {
                  html += "<a href='javascript:remove_user(\"" + member.uid + "\");' class='badge'>REMOVE</a>";
                }
              }
              return $("#team-members").html(html);
            }
          });
        }
      } else {
        return location.href = "/login";
      }
    });
  };

  this.remove_user = function(uid) {
    return api_call("POST", "api/team/remove", {
      uid: uid,
      confirm: $("#leave_confirm").val()
    }).done(function(result) {
      if (result.success === 1) {
        $("#member_" + uid).slideUp("fast");
      }
      return display_message("#remove_" + uid, (result.success === 1 ? 'success' : 'danger'), result.message, function() {
        if (result.success === 1) {
          return window.location.reload(true);
        }
      });
    });
  };

  this.join_team = function() {
    $("[id^=join-]").attr("disabled", "disabled");
    return api_call("POST", "/api/team/join", {
      join_code: $("#join-code").val()
    }).done(function(result) {
      if (result.success !== 1) {
        $("[id^=join-]").removeAttr("disabled");
      }
      return display_message("#join_msg", (result.success === 1 ? 'success' : 'danger'), result.message, function() {
        if (result.success === 1) {
          return window.location.reload(true);
        }
      });
    });
  };

  this.create_team = function() {
    $("[id^=create-]").attr("disabled", "disabled");
    return api_call("POST", "/api/team/create", {
      teamname: $("#create-name").val()
    }).done(function(result) {
      if (result.success === 1) {
        return display_message("#create_msg", "success", result.message, function() {
          return window.location.reload(true);
        });
      } else {
        display_message("#create_msg", "danger", result.message);
        return $("[id^=create-]").removeAttr("disabled");
      }
    });
  };

  this.toggle_join_code = function() {
    if ($('#team-join-code').attr('type') === 'text') {
      return $('#team-join-code').attr('type', 'password');
    } else if ($('#team-join-code').attr('type') === 'password') {
      return $('#team-join-code').attr('type', 'text');
    }
  };

  this.generate_join_code = function() {
    return api_call("POST", "/api/team/join_code/new", {}).done(function(result) {
      if (result.success === 1) {
        $('#team-join-code').val(result.data);
        return $('#team-join-code').attr('type', 'text');
      }
    });
  };

  this.update_team = function() {
    return api_call("POST", "/api/team/update", {
      teamname: $("#team-name").val(),
      school: $("#team-school").val()
    }).done(function(result) {
      if (result.success === 1) {
        $("#saved_msg").css("display", "inline");
        return $("#saved_msg").fadeOut("slow");
      }
    });
  };

  this.update_info = function() {
    var to_disable;
    to_disable = "#update_info_form input[id^=account-]";
    ($(to_disable)).attr("disabled", "disabled");
    return api_call("POST", "/api/user/update", {
      name: $("#account-name").val(),
      nPassword: $("#account-password").val(),
      cPassword: $("#account-confirm").val()
    }).done(function(result) {
      if (result.success === 1) {
        return display_message("#update_user_msg", "success", result.message, function() {
          return location.reload(true);
        });
      } else {
        display_message("#update_user_msg", "danger", result.message);
        return ($(to_disable)).removeAttr("disabled");
      }
    });
  };

  this.post_update = function() {
    var content;
    content = CKEDITOR.instances["update-content"].getData();
    return api_call("POST", "/api/updates/post", {
      title: $("#update-title").val(),
      content: content
    }).done(function(result) {
      if (result.success === 1) {
        console.log(result);
      }
      return display_message("#update_msg", (result.success === 1 ? 'success' : 'danger'), result.message, function() {
        if (result.success === 1) {
          return window.location.reload(true);
        }
      });
    });
  };

  $(function() {
    redirect_if_not_logged_in();
    return load_account_page();
  });

}).call(this);
