// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    redirect_if_not_logged_in(true);
    return api_call("GET", "/api/problem/e_solved", {}).done(function(result) {
      var egg, html, i, len, ref;
      if (result.success === 1) {
        html = "";
        ref = result.data;
        for (i = 0, len = ref.length; i < len; i++) {
          egg = ref[i];
          html += "<li class='list-group-item'>" + egg + "</li>";
        }
        return $("#collected_eggs").html(html);
      }
    });
  });

  this.submit_egg = function() {
    return api_call("POST", "/api/problem/e_submit", {
      answer: $("#egg").val()
    }).done(function(result) {
      if (result.success === 1) {
        return display_message("#egg_msg", (result.data.correct === 1 ? 'success' : 'danger'), result.data.message, function() {
          if (result.data.correct === true) {
            return location.reload(true);
          }
        });
      } else {
        return display_message("#egg_msg", "danger", result.message);
      }
    });
  };

}).call(this);
