// Generated by CoffeeScript 1.10.0
(function() {
  var handle_login;

  handle_login = function(e) {
    var data, to_disable;
    e.preventDefault();
    data = $("#login_form").serializeObject();
    to_disable = "#login_form input, #login_form select";
    $(to_disable).attr("disabled", "disabled");
    api_call("POST", "/api/user/login", data).done(function(result) {
      var class_name;
      class_name = result.success === 1 ? "success" : "warning";
      display_message("#login_msg", class_name, result.message, function() {
        if (result.success === 1) {
          return location.href = "/account";
        }
      });
      $(to_disable).removeAttr("disabled");
      return grecaptcha.reset();
    }).fail(function() {
      display_message("#login_msg", "danger", "Couldn't connect to the API.");
      $(to_disable).removeAttr("disabled");
      return grecaptcha.reset();
    });
    return false;
  };

  $(function() {
    return $("#login_form").on("submit", handle_login);
  });

}).call(this);
