// Generated by CoffeeScript 1.10.0
(function() {
  this.load_problems = function() {
    return api_call("GET", "/api/user/info", {}).done(function(result) {
      var render_problem, render_problem_list;
      if (result["success"] === 1 && result["data"]["team"].length > 0) {
        render_problem_list = _.template($("#template_problem_list").remove().text());
        render_problem = _.template($("#template_problem").remove().text());
        return api_call("GET", "/api/problem/get_unlocked", {}).done(function(result) {
          if (result.success === 1) {
            if (result["show_rules"]) {
              $("#rules").slideDown("fast");
            }
            if (result["unlocked"] === result["total"]) {
              $("#problems_count").html("<div class='alert alert-success'>You've unlocked all <b>" + result["total"] + "</b> problems!</div>");
            } else {
              $("#problems_count").html("");
            }
            $("#problems_container").html(render_problem_list({
              problems: result.data,
              render_problem: render_problem,
              cardinal: ["1st", "2nd", "3rd"]
            }));
            return $('.solved').parent().parent().next().hide();
          } else {
            return display_message_permanent("#problems_msg", "danger", result.message);
          }
        });
      } else {
        return display_message_permanent("#problems_msg", "warning", "You must be in a team to view problems! Click <a href='/account' class='text-danger'>here</a> to join or create a team!");
      }
    });
  };

  this.show_hint = function(id) {
    $('#hint_' + id).slideToggle(120, "swing");
  };

  this.handle_submit = function(id) {
    return api_call("POST", "/api/problem/submit", {
      pid: id,
      answer: $("#" + id).val()
    }).done(function(result) {
      if (result.success === 1) {
        return display_message("#msg_" + id, (result.data.correct === true ? 'success' : 'danger'), result.data.message, function() {
          if (result.data.correct === true) {
            return location.reload(true);
          }
        });
      } else {
        return display_message("#msg_" + id, "danger", result.message);
      }
    });
  };

  $(function() {
    load_problems();
    return redirect_if_not_logged_in(true);
  });

}).call(this);
