// Generated by CoffeeScript 1.10.0
(function() {
  var handle_register;

  handle_register = function(e) {
    var data, to_disable;
    e.preventDefault();
    data = $("#register_form").serializeObject();
    to_disable = "#register_form input, #register_form select";
    $(to_disable).attr("disabled", "disabled");
    api_call("POST", "/api/user/create", data).done(function(result) {
      var class_name;
      class_name = result.success === 1 ? "success" : "warning";
      display_message("#register_msg", class_name, result.message);
      if (result.success === 1) {
        location.href = "/account";
      } else {
        $(to_disable).removeAttr("disabled");
      }
      return grecaptcha.reset();
    }).fail(function() {
      display_message("#register_msg", "danger", "Couldn't connect to the API.");
      $(to_disable).removeAttr("disabled");
      return grecaptcha.reset();
    });
    return false;
  };

  $(function() {
    return $("#register_form").on("submit", handle_register);
  });

}).call(this);
