// Generated by CoffeeScript 1.10.0
(function() {
  this.retrieve_credentials = function() {
    return api_call("GET", "/api/team/shell").done(function(result) {
      if (result.success === 1) {
        return $("#credentials").html("username: <code>" + result.user + "</code> | password: <code>" + result.pass + "</code>. For SSH, <code>ssh " + result.user + "@ssh.easyctf.com</code>.");
      } else {
        return $("#credentials").html("Retrieving failed... <a href='javascript:retrieve_credentials();' class='btn btn-info'>try again?</a>");
      }
    });
  };

  $(function() {
    return redirect_if_not_logged_in(true);
  });

}).call(this);
