// Generated by CoffeeScript 1.10.0
(function() {
  $(function() {
    var username;
    username = decodeURIComponent(location.search.substring(1));
    $(".username").html(htmlEntities(username));
    return document.title = "User " + htmlEntities(username) + " - EasyCTF 2015";
  });

}).call(this);
